### PR TITLE
Added trailing slash to downloads page

### PR DESCRIPTION
**Pull request by Ardakilic**
The download link was giving 404 because of lacking trailing slash in README, this fixes it.

### CODE REVIEW

**Comment by dragoonis** [comment]
@Ardakilic something is wrong with this PR - it is showing 250+ commits. Can you make this just 1 commit with your fix?

**Comment by Ardakilic** [comment]
@dragoonis No idea how that happened :confused: It was just this: https://github.com/Ardakilic/framework/commit/d79bd5d3dd4d707978f75a88b3fa5c26b287c810 , I'll close this and re-open a new one this evening.

**Comment by rawkode** [comment]
That's because the PR was created before the big history rewrite in the sky :smile:

**Comment by dragoonis** [comment]
@rawkode that would have been me then. :(

**Pull request closed without merging**
