### PR TITLE
Applying a fix for registerCommands(). 

### PR DESCRIPTION
**Pull request by dragoonis**
There's now a getCommandsPath() method on the base module which all child modules can modify

/cc @noisebleed

### CODE REVIEW

**Comment by noisebleed** [comment]
@dragoonis don't you want this in `master` also?

**Comment by dragoonis** [comment]
@noisebleed yes I do! You wanna pop it in there?

**Comment by noisebleed** [comment]
@dragoonis done.

**Comment by dragoonis** [comment]
@noisebleed thank you

**Pull request merged**
